FROM node:22-slim

ARG DB_NAME_REMOTE
ARG DB_USER_REMOTE
ARG DB_PASSWORD_REMOTE
ARG DB_HOST_REMOTE
ARG DB_DIALECT_REMOTE
ARG DB_PORT_REMOTE
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET
ARG PORT
ARG ACCESS_TOKEN_LIFETIME
ARG REFRESH_TOKEN_LIFETIME
ARG MAIL_TRAP_USER
ARG MAIL_TRAP_PASSWORD
ARG DB_ENV


ENV DB_NAME_REMOTE=$DB_NAME_REMOTE
ENV DB_USER_REMOTE=$DB_USER_REMOTE
ENV DB_PASSWORD_REMOTE=$DB_PASSWORD_REMOTE
ENV DB_HOST_REMOTE=$DB_HOST_REMOTE
ENV DB_DIALECT_REMOTE=$DB_DIALECT_REMOTE
ENV DB_PORT_REMOTE=$DB_PORT_REMOTE
ENV JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
ENV JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
ENV PORT=$PORT
ENV ACCESS_TOKEN_LIFETIME=$ACCESS_TOKEN_LIFETIME
ENV REFRESH_TOKEN_LIFETIME=$REFRESH_TOKEN_LIFETIME
ENV MAIL_TRAP_USER=$MAIL_TRAP_USER
ENV MAIL_TRAP_PASSWORD=$MAIL_TRAP_PASSWORD
ENV DB_ENV=$DB_ENV

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm install -g typescript

RUN tsc

EXPOSE 3000

CMD ["npm", "run", "start"]
